#cloud-config
autoinstall:
  version: 1

  identity:
    realname: "Ubuntu User"
    username: ubuntu
    password: "$6$rounds=4096$PASSWORD_PLACEHOLDER"

  hostname: "{{extra_hostname}}"

  timezone: "{{extra_timezone}}"

  keyboard:
    layout: "us"

  ssh:
    install-server: true
    authorized-keys: []
    allow-pw: true

  storage:
    grub:
      reorder_uefi: false

  user-data:
    disable_root: false
    ssh_pwauth: true

  late-commands:
    - curtin in-target -- bash -c "echo 'root:$(cat /var/tmp/root-pass)' | chpasswd"
    - curtin in-target -- bash -c "timedatectl set-timezone '{{extra_timezone}}'"
    - curtin in-target -- bash -c "hostnamectl set-hostname '{{extra_hostname}}'"

  early-commands:
    - echo "{{PASSWORD_CLEAR}}" >/var/tmp/root-pass
    - /cdrom/ubuntu-storage-early.sh
    - >
      if [ "{{extra_cache_size}}" != "" ]; then
        echo "swap:size={{extra_cache_size}}M" >> /autoinstall.yaml
      fi
